import type { Group } from "./types";

export const mockGroups: Group[] = [
  {
    id: "1",
    name: "Engenharia de Software",
    description: "Discussões sobre padrões de projeto, arquitetura e boas práticas.",
    icon: "💻",
    authorId: "mock",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: null,
    memberCount: 42,
    isMember: false,
  },
  {
    id: "2",
    name: "Inteligência Artificial",
    description: "Artigos, experimentos e projetos de IA e Machine Learning.",
    icon: "🤖",
    authorId: "mock",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: null,
    memberCount: 78,
    isMember: false,
  },
  {
    id: "3",
    name: "Desenvolvimento Web",
    description: "Front-end, back-end, DevOps e tudo sobre a web moderna.",
    icon: "🌐",
    authorId: "mock",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: null,
    memberCount: 95,
    isMember: false,
  },
  {
    id: "4",
    name: "Pesquisa & Inovação",
    description: "Grupo voltado a iniciação científica e trabalhos acadêmicos.",
    icon: "🔬",
    authorId: "mock",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    author: null,
    memberCount: 31,
    isMember: false,
  },
];
